### ISSUE TITLE
Kodrad saknas

### ISSUE THREAD

**Issue by albinekb** [Nackademin/code-mode-windows#2]
[Den här randen](https://github.com/Nackademin/code-mode-windows/blob/master/no_fun_for_you/flow-warning.py#L12) på er [hemsida](https://codemode.co/script/no-fun-for-you/)
![image](https://cloud.githubusercontent.com/assets/5027156/14160919/053a80d6-f6e0-11e5-8bcd-aff75cb1765e.png)
:dancer:

**Comment by nackademin-codemode** [comment]
Nu är det fixat. Tack för att du uppmärksammade det!
